// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/examples/StockMsg.proto

package org.examples;

public final class StockProtoMessage {
  private StockProtoMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Stock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 entryId = 1;</code>
     * @return The entryId.
     */
    int getEntryId();

    /**
     * <code>string symbol = 2;</code>
     * @return The symbol.
     */
    java.lang.String getSymbol();
    /**
     * <code>string symbol = 2;</code>
     * @return The bytes for symbol.
     */
    com.google.protobuf.ByteString
        getSymbolBytes();

    /**
     * <code>double sharePrice = 3;</code>
     * @return The sharePrice.
     */
    double getSharePrice();

    /**
     * <code>.proto.InnerStock innerStock = 4;</code>
     * @return Whether the innerStock field is set.
     */
    boolean hasInnerStock();
    /**
     * <code>.proto.InnerStock innerStock = 4;</code>
     * @return The innerStock.
     */
    org.examples.StockProtoMessage.InnerStock getInnerStock();
    /**
     * <code>.proto.InnerStock innerStock = 4;</code>
     */
    org.examples.StockProtoMessage.InnerStockOrBuilder getInnerStockOrBuilder();

    /**
     * <code>map&lt;string, string&gt; maps = 5;</code>
     */
    int getMapsCount();
    /**
     * <code>map&lt;string, string&gt; maps = 5;</code>
     */
    boolean containsMaps(
        java.lang.String key);
    /**
     * Use {@link #getMapsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMaps();
    /**
     * <code>map&lt;string, string&gt; maps = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMapsMap();
    /**
     * <code>map&lt;string, string&gt; maps = 5;</code>
     */

    java.lang.String getMapsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; maps = 5;</code>
     */

    java.lang.String getMapsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code proto.Stock}
   */
  public static final class Stock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Stock)
      StockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Stock.newBuilder() to construct.
    private Stock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Stock() {
      symbol_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Stock();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Stock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              entryId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              symbol_ = s;
              break;
            }
            case 25: {

              sharePrice_ = input.readDouble();
              break;
            }
            case 34: {
              org.examples.StockProtoMessage.InnerStock.Builder subBuilder = null;
              if (innerStock_ != null) {
                subBuilder = innerStock_.toBuilder();
              }
              innerStock_ = input.readMessage(org.examples.StockProtoMessage.InnerStock.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(innerStock_);
                innerStock_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                maps_ = com.google.protobuf.MapField.newMapField(
                    MapsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              maps__ = input.readMessage(
                  MapsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              maps_.getMutableMap().put(
                  maps__.getKey(), maps__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.examples.StockProtoMessage.internal_static_proto_Stock_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMaps();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.examples.StockProtoMessage.internal_static_proto_Stock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.examples.StockProtoMessage.Stock.class, org.examples.StockProtoMessage.Stock.Builder.class);
    }

    public static final int ENTRYID_FIELD_NUMBER = 1;
    private int entryId_;
    /**
     * <code>int32 entryId = 1;</code>
     * @return The entryId.
     */
    @java.lang.Override
    public int getEntryId() {
      return entryId_;
    }

    public static final int SYMBOL_FIELD_NUMBER = 2;
    private volatile java.lang.Object symbol_;
    /**
     * <code>string symbol = 2;</code>
     * @return The symbol.
     */
    @java.lang.Override
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      }
    }
    /**
     * <code>string symbol = 2;</code>
     * @return The bytes for symbol.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHAREPRICE_FIELD_NUMBER = 3;
    private double sharePrice_;
    /**
     * <code>double sharePrice = 3;</code>
     * @return The sharePrice.
     */
    @java.lang.Override
    public double getSharePrice() {
      return sharePrice_;
    }

    public static final int INNERSTOCK_FIELD_NUMBER = 4;
    private org.examples.StockProtoMessage.InnerStock innerStock_;
    /**
     * <code>.proto.InnerStock innerStock = 4;</code>
     * @return Whether the innerStock field is set.
     */
    @java.lang.Override
    public boolean hasInnerStock() {
      return innerStock_ != null;
    }
    /**
     * <code>.proto.InnerStock innerStock = 4;</code>
     * @return The innerStock.
     */
    @java.lang.Override
    public org.examples.StockProtoMessage.InnerStock getInnerStock() {
      return innerStock_ == null ? org.examples.StockProtoMessage.InnerStock.getDefaultInstance() : innerStock_;
    }
    /**
     * <code>.proto.InnerStock innerStock = 4;</code>
     */
    @java.lang.Override
    public org.examples.StockProtoMessage.InnerStockOrBuilder getInnerStockOrBuilder() {
      return getInnerStock();
    }

    public static final int MAPS_FIELD_NUMBER = 5;
    private static final class MapsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  org.examples.StockProtoMessage.internal_static_proto_Stock_MapsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> maps_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMaps() {
      if (maps_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapsDefaultEntryHolder.defaultEntry);
      }
      return maps_;
    }

    public int getMapsCount() {
      return internalGetMaps().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; maps = 5;</code>
     */

    @java.lang.Override
    public boolean containsMaps(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMaps().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMaps() {
      return getMapsMap();
    }
    /**
     * <code>map&lt;string, string&gt; maps = 5;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMapsMap() {
      return internalGetMaps().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; maps = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getMapsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMaps().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; maps = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getMapsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMaps().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (entryId_ != 0) {
        output.writeInt32(1, entryId_);
      }
      if (!getSymbolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, symbol_);
      }
      if (sharePrice_ != 0D) {
        output.writeDouble(3, sharePrice_);
      }
      if (innerStock_ != null) {
        output.writeMessage(4, getInnerStock());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMaps(),
          MapsDefaultEntryHolder.defaultEntry,
          5);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (entryId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, entryId_);
      }
      if (!getSymbolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, symbol_);
      }
      if (sharePrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, sharePrice_);
      }
      if (innerStock_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getInnerStock());
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMaps().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        maps__ = MapsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, maps__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.examples.StockProtoMessage.Stock)) {
        return super.equals(obj);
      }
      org.examples.StockProtoMessage.Stock other = (org.examples.StockProtoMessage.Stock) obj;

      if (getEntryId()
          != other.getEntryId()) return false;
      if (!getSymbol()
          .equals(other.getSymbol())) return false;
      if (java.lang.Double.doubleToLongBits(getSharePrice())
          != java.lang.Double.doubleToLongBits(
              other.getSharePrice())) return false;
      if (hasInnerStock() != other.hasInnerStock()) return false;
      if (hasInnerStock()) {
        if (!getInnerStock()
            .equals(other.getInnerStock())) return false;
      }
      if (!internalGetMaps().equals(
          other.internalGetMaps())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENTRYID_FIELD_NUMBER;
      hash = (53 * hash) + getEntryId();
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol().hashCode();
      hash = (37 * hash) + SHAREPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSharePrice()));
      if (hasInnerStock()) {
        hash = (37 * hash) + INNERSTOCK_FIELD_NUMBER;
        hash = (53 * hash) + getInnerStock().hashCode();
      }
      if (!internalGetMaps().getMap().isEmpty()) {
        hash = (37 * hash) + MAPS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMaps().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.examples.StockProtoMessage.Stock parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.examples.StockProtoMessage.Stock parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.examples.StockProtoMessage.Stock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.examples.StockProtoMessage.Stock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.examples.StockProtoMessage.Stock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.examples.StockProtoMessage.Stock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.examples.StockProtoMessage.Stock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.examples.StockProtoMessage.Stock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.examples.StockProtoMessage.Stock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.examples.StockProtoMessage.Stock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.examples.StockProtoMessage.Stock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.examples.StockProtoMessage.Stock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.examples.StockProtoMessage.Stock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Stock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Stock)
        org.examples.StockProtoMessage.StockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.examples.StockProtoMessage.internal_static_proto_Stock_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMaps();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableMaps();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.examples.StockProtoMessage.internal_static_proto_Stock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.examples.StockProtoMessage.Stock.class, org.examples.StockProtoMessage.Stock.Builder.class);
      }

      // Construct using org.examples.StockProtoMessage.Stock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        entryId_ = 0;

        symbol_ = "";

        sharePrice_ = 0D;

        if (innerStockBuilder_ == null) {
          innerStock_ = null;
        } else {
          innerStock_ = null;
          innerStockBuilder_ = null;
        }
        internalGetMutableMaps().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.examples.StockProtoMessage.internal_static_proto_Stock_descriptor;
      }

      @java.lang.Override
      public org.examples.StockProtoMessage.Stock getDefaultInstanceForType() {
        return org.examples.StockProtoMessage.Stock.getDefaultInstance();
      }

      @java.lang.Override
      public org.examples.StockProtoMessage.Stock build() {
        org.examples.StockProtoMessage.Stock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.examples.StockProtoMessage.Stock buildPartial() {
        org.examples.StockProtoMessage.Stock result = new org.examples.StockProtoMessage.Stock(this);
        int from_bitField0_ = bitField0_;
        result.entryId_ = entryId_;
        result.symbol_ = symbol_;
        result.sharePrice_ = sharePrice_;
        if (innerStockBuilder_ == null) {
          result.innerStock_ = innerStock_;
        } else {
          result.innerStock_ = innerStockBuilder_.build();
        }
        result.maps_ = internalGetMaps();
        result.maps_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.examples.StockProtoMessage.Stock) {
          return mergeFrom((org.examples.StockProtoMessage.Stock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.examples.StockProtoMessage.Stock other) {
        if (other == org.examples.StockProtoMessage.Stock.getDefaultInstance()) return this;
        if (other.getEntryId() != 0) {
          setEntryId(other.getEntryId());
        }
        if (!other.getSymbol().isEmpty()) {
          symbol_ = other.symbol_;
          onChanged();
        }
        if (other.getSharePrice() != 0D) {
          setSharePrice(other.getSharePrice());
        }
        if (other.hasInnerStock()) {
          mergeInnerStock(other.getInnerStock());
        }
        internalGetMutableMaps().mergeFrom(
            other.internalGetMaps());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.examples.StockProtoMessage.Stock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.examples.StockProtoMessage.Stock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int entryId_ ;
      /**
       * <code>int32 entryId = 1;</code>
       * @return The entryId.
       */
      @java.lang.Override
      public int getEntryId() {
        return entryId_;
      }
      /**
       * <code>int32 entryId = 1;</code>
       * @param value The entryId to set.
       * @return This builder for chaining.
       */
      public Builder setEntryId(int value) {
        
        entryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 entryId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEntryId() {
        
        entryId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object symbol_ = "";
      /**
       * <code>string symbol = 2;</code>
       * @return The symbol.
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string symbol = 2;</code>
       * @return The bytes for symbol.
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string symbol = 2;</code>
       * @param value The symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        symbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSymbol() {
        
        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 2;</code>
       * @param value The bytes for symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        symbol_ = value;
        onChanged();
        return this;
      }

      private double sharePrice_ ;
      /**
       * <code>double sharePrice = 3;</code>
       * @return The sharePrice.
       */
      @java.lang.Override
      public double getSharePrice() {
        return sharePrice_;
      }
      /**
       * <code>double sharePrice = 3;</code>
       * @param value The sharePrice to set.
       * @return This builder for chaining.
       */
      public Builder setSharePrice(double value) {
        
        sharePrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double sharePrice = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSharePrice() {
        
        sharePrice_ = 0D;
        onChanged();
        return this;
      }

      private org.examples.StockProtoMessage.InnerStock innerStock_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.examples.StockProtoMessage.InnerStock, org.examples.StockProtoMessage.InnerStock.Builder, org.examples.StockProtoMessage.InnerStockOrBuilder> innerStockBuilder_;
      /**
       * <code>.proto.InnerStock innerStock = 4;</code>
       * @return Whether the innerStock field is set.
       */
      public boolean hasInnerStock() {
        return innerStockBuilder_ != null || innerStock_ != null;
      }
      /**
       * <code>.proto.InnerStock innerStock = 4;</code>
       * @return The innerStock.
       */
      public org.examples.StockProtoMessage.InnerStock getInnerStock() {
        if (innerStockBuilder_ == null) {
          return innerStock_ == null ? org.examples.StockProtoMessage.InnerStock.getDefaultInstance() : innerStock_;
        } else {
          return innerStockBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.InnerStock innerStock = 4;</code>
       */
      public Builder setInnerStock(org.examples.StockProtoMessage.InnerStock value) {
        if (innerStockBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          innerStock_ = value;
          onChanged();
        } else {
          innerStockBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.InnerStock innerStock = 4;</code>
       */
      public Builder setInnerStock(
          org.examples.StockProtoMessage.InnerStock.Builder builderForValue) {
        if (innerStockBuilder_ == null) {
          innerStock_ = builderForValue.build();
          onChanged();
        } else {
          innerStockBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.InnerStock innerStock = 4;</code>
       */
      public Builder mergeInnerStock(org.examples.StockProtoMessage.InnerStock value) {
        if (innerStockBuilder_ == null) {
          if (innerStock_ != null) {
            innerStock_ =
              org.examples.StockProtoMessage.InnerStock.newBuilder(innerStock_).mergeFrom(value).buildPartial();
          } else {
            innerStock_ = value;
          }
          onChanged();
        } else {
          innerStockBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.InnerStock innerStock = 4;</code>
       */
      public Builder clearInnerStock() {
        if (innerStockBuilder_ == null) {
          innerStock_ = null;
          onChanged();
        } else {
          innerStock_ = null;
          innerStockBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.InnerStock innerStock = 4;</code>
       */
      public org.examples.StockProtoMessage.InnerStock.Builder getInnerStockBuilder() {
        
        onChanged();
        return getInnerStockFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.InnerStock innerStock = 4;</code>
       */
      public org.examples.StockProtoMessage.InnerStockOrBuilder getInnerStockOrBuilder() {
        if (innerStockBuilder_ != null) {
          return innerStockBuilder_.getMessageOrBuilder();
        } else {
          return innerStock_ == null ?
              org.examples.StockProtoMessage.InnerStock.getDefaultInstance() : innerStock_;
        }
      }
      /**
       * <code>.proto.InnerStock innerStock = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.examples.StockProtoMessage.InnerStock, org.examples.StockProtoMessage.InnerStock.Builder, org.examples.StockProtoMessage.InnerStockOrBuilder> 
          getInnerStockFieldBuilder() {
        if (innerStockBuilder_ == null) {
          innerStockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.examples.StockProtoMessage.InnerStock, org.examples.StockProtoMessage.InnerStock.Builder, org.examples.StockProtoMessage.InnerStockOrBuilder>(
                  getInnerStock(),
                  getParentForChildren(),
                  isClean());
          innerStock_ = null;
        }
        return innerStockBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> maps_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMaps() {
        if (maps_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MapsDefaultEntryHolder.defaultEntry);
        }
        return maps_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableMaps() {
        onChanged();;
        if (maps_ == null) {
          maps_ = com.google.protobuf.MapField.newMapField(
              MapsDefaultEntryHolder.defaultEntry);
        }
        if (!maps_.isMutable()) {
          maps_ = maps_.copy();
        }
        return maps_;
      }

      public int getMapsCount() {
        return internalGetMaps().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; maps = 5;</code>
       */

      @java.lang.Override
      public boolean containsMaps(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMaps().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMapsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMaps() {
        return getMapsMap();
      }
      /**
       * <code>map&lt;string, string&gt; maps = 5;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getMapsMap() {
        return internalGetMaps().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; maps = 5;</code>
       */
      @java.lang.Override

      public java.lang.String getMapsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMaps().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; maps = 5;</code>
       */
      @java.lang.Override

      public java.lang.String getMapsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMaps().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMaps() {
        internalGetMutableMaps().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; maps = 5;</code>
       */

      public Builder removeMaps(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMaps().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableMaps() {
        return internalGetMutableMaps().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; maps = 5;</code>
       */
      public Builder putMaps(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMaps().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; maps = 5;</code>
       */

      public Builder putAllMaps(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMaps().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Stock)
    }

    // @@protoc_insertion_point(class_scope:proto.Stock)
    private static final org.examples.StockProtoMessage.Stock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.examples.StockProtoMessage.Stock();
    }

    public static org.examples.StockProtoMessage.Stock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Stock>
        PARSER = new com.google.protobuf.AbstractParser<Stock>() {
      @java.lang.Override
      public Stock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Stock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Stock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Stock> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.examples.StockProtoMessage.Stock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InnerStockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.InnerStock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 entryId = 1;</code>
     * @return The entryId.
     */
    int getEntryId();

    /**
     * <code>string symbol = 2;</code>
     * @return The symbol.
     */
    java.lang.String getSymbol();
    /**
     * <code>string symbol = 2;</code>
     * @return The bytes for symbol.
     */
    com.google.protobuf.ByteString
        getSymbolBytes();

    /**
     * <code>double sharePrice = 3;</code>
     * @return The sharePrice.
     */
    double getSharePrice();
  }
  /**
   * Protobuf type {@code proto.InnerStock}
   */
  public static final class InnerStock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.InnerStock)
      InnerStockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InnerStock.newBuilder() to construct.
    private InnerStock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InnerStock() {
      symbol_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InnerStock();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InnerStock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              entryId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              symbol_ = s;
              break;
            }
            case 25: {

              sharePrice_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.examples.StockProtoMessage.internal_static_proto_InnerStock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.examples.StockProtoMessage.internal_static_proto_InnerStock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.examples.StockProtoMessage.InnerStock.class, org.examples.StockProtoMessage.InnerStock.Builder.class);
    }

    public static final int ENTRYID_FIELD_NUMBER = 1;
    private int entryId_;
    /**
     * <code>int32 entryId = 1;</code>
     * @return The entryId.
     */
    @java.lang.Override
    public int getEntryId() {
      return entryId_;
    }

    public static final int SYMBOL_FIELD_NUMBER = 2;
    private volatile java.lang.Object symbol_;
    /**
     * <code>string symbol = 2;</code>
     * @return The symbol.
     */
    @java.lang.Override
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      }
    }
    /**
     * <code>string symbol = 2;</code>
     * @return The bytes for symbol.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHAREPRICE_FIELD_NUMBER = 3;
    private double sharePrice_;
    /**
     * <code>double sharePrice = 3;</code>
     * @return The sharePrice.
     */
    @java.lang.Override
    public double getSharePrice() {
      return sharePrice_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (entryId_ != 0) {
        output.writeInt32(1, entryId_);
      }
      if (!getSymbolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, symbol_);
      }
      if (sharePrice_ != 0D) {
        output.writeDouble(3, sharePrice_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (entryId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, entryId_);
      }
      if (!getSymbolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, symbol_);
      }
      if (sharePrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, sharePrice_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.examples.StockProtoMessage.InnerStock)) {
        return super.equals(obj);
      }
      org.examples.StockProtoMessage.InnerStock other = (org.examples.StockProtoMessage.InnerStock) obj;

      if (getEntryId()
          != other.getEntryId()) return false;
      if (!getSymbol()
          .equals(other.getSymbol())) return false;
      if (java.lang.Double.doubleToLongBits(getSharePrice())
          != java.lang.Double.doubleToLongBits(
              other.getSharePrice())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENTRYID_FIELD_NUMBER;
      hash = (53 * hash) + getEntryId();
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol().hashCode();
      hash = (37 * hash) + SHAREPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSharePrice()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.examples.StockProtoMessage.InnerStock parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.examples.StockProtoMessage.InnerStock parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.examples.StockProtoMessage.InnerStock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.examples.StockProtoMessage.InnerStock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.examples.StockProtoMessage.InnerStock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.examples.StockProtoMessage.InnerStock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.examples.StockProtoMessage.InnerStock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.examples.StockProtoMessage.InnerStock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.examples.StockProtoMessage.InnerStock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.examples.StockProtoMessage.InnerStock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.examples.StockProtoMessage.InnerStock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.examples.StockProtoMessage.InnerStock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.examples.StockProtoMessage.InnerStock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.InnerStock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.InnerStock)
        org.examples.StockProtoMessage.InnerStockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.examples.StockProtoMessage.internal_static_proto_InnerStock_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.examples.StockProtoMessage.internal_static_proto_InnerStock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.examples.StockProtoMessage.InnerStock.class, org.examples.StockProtoMessage.InnerStock.Builder.class);
      }

      // Construct using org.examples.StockProtoMessage.InnerStock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        entryId_ = 0;

        symbol_ = "";

        sharePrice_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.examples.StockProtoMessage.internal_static_proto_InnerStock_descriptor;
      }

      @java.lang.Override
      public org.examples.StockProtoMessage.InnerStock getDefaultInstanceForType() {
        return org.examples.StockProtoMessage.InnerStock.getDefaultInstance();
      }

      @java.lang.Override
      public org.examples.StockProtoMessage.InnerStock build() {
        org.examples.StockProtoMessage.InnerStock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.examples.StockProtoMessage.InnerStock buildPartial() {
        org.examples.StockProtoMessage.InnerStock result = new org.examples.StockProtoMessage.InnerStock(this);
        result.entryId_ = entryId_;
        result.symbol_ = symbol_;
        result.sharePrice_ = sharePrice_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.examples.StockProtoMessage.InnerStock) {
          return mergeFrom((org.examples.StockProtoMessage.InnerStock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.examples.StockProtoMessage.InnerStock other) {
        if (other == org.examples.StockProtoMessage.InnerStock.getDefaultInstance()) return this;
        if (other.getEntryId() != 0) {
          setEntryId(other.getEntryId());
        }
        if (!other.getSymbol().isEmpty()) {
          symbol_ = other.symbol_;
          onChanged();
        }
        if (other.getSharePrice() != 0D) {
          setSharePrice(other.getSharePrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.examples.StockProtoMessage.InnerStock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.examples.StockProtoMessage.InnerStock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int entryId_ ;
      /**
       * <code>int32 entryId = 1;</code>
       * @return The entryId.
       */
      @java.lang.Override
      public int getEntryId() {
        return entryId_;
      }
      /**
       * <code>int32 entryId = 1;</code>
       * @param value The entryId to set.
       * @return This builder for chaining.
       */
      public Builder setEntryId(int value) {
        
        entryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 entryId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEntryId() {
        
        entryId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object symbol_ = "";
      /**
       * <code>string symbol = 2;</code>
       * @return The symbol.
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string symbol = 2;</code>
       * @return The bytes for symbol.
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string symbol = 2;</code>
       * @param value The symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        symbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSymbol() {
        
        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 2;</code>
       * @param value The bytes for symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        symbol_ = value;
        onChanged();
        return this;
      }

      private double sharePrice_ ;
      /**
       * <code>double sharePrice = 3;</code>
       * @return The sharePrice.
       */
      @java.lang.Override
      public double getSharePrice() {
        return sharePrice_;
      }
      /**
       * <code>double sharePrice = 3;</code>
       * @param value The sharePrice to set.
       * @return This builder for chaining.
       */
      public Builder setSharePrice(double value) {
        
        sharePrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double sharePrice = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSharePrice() {
        
        sharePrice_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.InnerStock)
    }

    // @@protoc_insertion_point(class_scope:proto.InnerStock)
    private static final org.examples.StockProtoMessage.InnerStock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.examples.StockProtoMessage.InnerStock();
    }

    public static org.examples.StockProtoMessage.InnerStock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InnerStock>
        PARSER = new com.google.protobuf.AbstractParser<InnerStock>() {
      @java.lang.Override
      public InnerStock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InnerStock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InnerStock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InnerStock> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.examples.StockProtoMessage.InnerStock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Stock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Stock_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Stock_MapsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Stock_MapsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_InnerStock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_InnerStock_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033org/examples/StockMsg.proto\022\005proto\"\266\001\n" +
      "\005Stock\022\017\n\007entryId\030\001 \001(\005\022\016\n\006symbol\030\002 \001(\t\022" +
      "\022\n\nsharePrice\030\003 \001(\001\022%\n\ninnerStock\030\004 \001(\0132" +
      "\021.proto.InnerStock\022$\n\004maps\030\005 \003(\0132\026.proto" +
      ".Stock.MapsEntry\032+\n\tMapsEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"A\n\nInnerStock\022\017\n\007e" +
      "ntryId\030\001 \001(\005\022\016\n\006symbol\030\002 \001(\t\022\022\n\nsharePri" +
      "ce\030\003 \001(\001B!\n\014org.examplesB\021StockProtoMess" +
      "ageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_Stock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Stock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Stock_descriptor,
        new java.lang.String[] { "EntryId", "Symbol", "SharePrice", "InnerStock", "Maps", });
    internal_static_proto_Stock_MapsEntry_descriptor =
      internal_static_proto_Stock_descriptor.getNestedTypes().get(0);
    internal_static_proto_Stock_MapsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Stock_MapsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_proto_InnerStock_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_InnerStock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_InnerStock_descriptor,
        new java.lang.String[] { "EntryId", "Symbol", "SharePrice", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
